import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Physical AI & Humanoid Robotics course
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ROS 2 Fundamentals',
      items: [
        'modules/ros2-fundamentals/intro',
        'modules/ros2-fundamentals/chapter-1-introduction',
        'modules/ros2-fundamentals/chapter-2-nodes-topics-services',
        'modules/ros2-fundamentals/chapter-3-custom-messages',
        'modules/ros2-fundamentals/chapter-4-tools-debugging',
        'modules/ros2-fundamentals/lab-1-installation-setup',
        'modules/ros2-fundamentals/lab-2-publisher-subscriber',
        'modules/ros2-fundamentals/lab-3-services-actions',
        'modules/ros2-fundamentals/lab-4-custom-messages-launch',
        'modules/ros2-fundamentals/assessment',
      ],
    },
    {
      type: 'category',
      label: 'Simulation Environments',
      items: [
        'modules/simulation/intro',
        // Add simulation chapters when created
      ],
    },
    {
      type: 'category',
      label: 'NVIDIA Isaac Robotics',
      items: [
        'modules/nvidia-isaac/intro',
        // Add Isaac chapters when created
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) Models',
      items: [
        'modules/vla-integration/intro',
        // Add VLA chapters when created
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone/intro',
        // Add capstone content when created
      ],
    },
  ],
};

export default sidebars;
